name: Build Scala File to JAR

on:
  push:
    branches:
      - main  # Change this to your default branch
      - nithish
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your required Java version
          distribution: 'adopt'

      - name: Install sbt
        run: |
          echo "Installing sbt..."
          sudo apt-get update
          sudo apt-get install -y sbt

      - name: Create build.sbt file
        run: |
          echo "name := \samplejar" > build.sbt
          echo "version := \0.1" >> build.sbt
          echo "scalaVersion := \2.12" >> build.sbt
          echo "mainClass in Compile := Some(\"Main\")" >> build.sbt  # Adjust to your main class

      - name: Build with sbt
        run: sbt clean compile package

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: scala-jar
          path: target/scala-2.12/sample.jar  # Adjust according to your project structure
